In [2]:
import numpy as np

A =np.array([1,2,3])
B =np.array([4,3,0])
print('A+B = ',np.add(A,B))
print('A-B = ',np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [5]:
C = np.array([[1,2,3],[1,1,1]])
D = np.array([[4,3,9,9],[1,1,2,2],[4,2,1,1]])
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))
# print('np.multiply(C,D) C*D = ',np.multiply(C,D))

np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]


In [6]:
C@D

array([[18, 11, 16, 16],
       [ 9,  6, 12, 12]])

In [9]:
A-B

array([-3, -1,  3])

In [10]:
import sklearn